# AI-ASSISTED: Yes
# AI-TOOL: Claude Code
# PROMPT: Create Video Pydantic schemas
# DATE: 2026-04-19
# ENGINEER: System
# RISK-LEVEL: P2

from datetime import datetime

from pydantic import BaseModel, Field, field_validator

CODE_LENGTH = 3  # 视频编号固定长度


class VideoCreate(BaseModel):
    code: str = Field(..., min_length=3, max_length=3, pattern=r"^\d{3}$")
    name: str = Field(..., min_length=1, max_length=200)
    status: str = "active"

    @field_validator("code")
    @classmethod
    def validate_code(cls, v: str) -> str:
        if not v.isdigit() or len(v) != CODE_LENGTH:
            raise ValueError("编号必须是3位数字")
        return v


class VideoUpdate(BaseModel):
    name: str | None = Field(None, min_length=1, max_length=200)
    status: str | None = None
    cover_image: str | None = None  # read-only, auto-generated by process endpoint
    cultural_product_ids: list[int] | None = None


class VideoResponse(BaseModel):
    id: int
    code: str
    name: str
    file_path: str | None
    cover_image: str | None
    duration: float | None
    file_size: int | None
    status: str
    created_at: datetime

    class Config:
        from_attributes = True


class VideoProcessResponse(BaseModel):
    duration: float
    file_size: int
    resolution: str | None = None
    message: str
