#!/bin/bash
# =============================================================================
# ArtTouch NFC - SSL Certificate Setup (Let's Encrypt / Certbot)
# =============================================================================
# AI-ASSISTED: Yes
# AI-TOOL: Claude Code
# PROMPT: Create SSL setup script for Let's Encrypt with Nginx
# DATE: 2026-04-19
# ENGINEER: System
# RISK-LEVEL: P2
#
# Usage:
#   ./scripts/ssl-setup.sh                     # Interactive mode
#   ./scripts/ssl-setup.sh --renew            # Renew certificates
#   ./scripts/ssl-setup.sh --install          # First-time install + get cert
#
# Requirements:
#   - Nginx installed
#   - Domain pointing to this server
#   - Port 80 and 443 open

set -e

DOMAIN="${DOMAIN:-www.artouch.tech}"
EMAIL="${EMAIL:-admin@artouch.tech}"
CERT_DIR="/etc/letsencrypt/live/${DOMAIN}"
NGINX_SSL_CONF="/etc/nginx/sites-available/artouch-ssl"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

# Install certbot
install_certbot() {
    log_info "Installing certbot..."
    if command -v apt-get &> /dev/null; then
        apt-get update
        apt-get install -y certbot python3-certbot-nginx
    elif command -v yum &> /dev/null; then
        yum install -y certbot python3-certbot-nginx
    else
        log_error "Unsupported package manager"
        exit 1
    fi
    log_info "Certbot installed"
}

# Generate Nginx SSL template
generate_nginx_ssl() {
    log_info "Generating Nginx SSL configuration..."
    cat > "${NGINX_SSL_CONF}" << 'EOF'
# ArtTouch NFC - SSL-enabled Nginx Configuration
# Generated by ssl-setup.sh

server {
    listen 80;
    server_name DOMAIN_PLACEHOLDER;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name DOMAIN_PLACEHOLDER;

    # SSL Certificate
    ssl_certificate /etc/letsencrypt/live/DOMAIN_PLACEHOLDER/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/DOMAIN_PLACEHOLDER/privkey.pem;

    # SSL Security
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;

    # Modern SSL configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    # HSTS
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # OCSP Stapling
    ssl_stapling on;
    ssl_stapling_verify on;

    # Limit upload size
    client_max_body_size 200M;

    # Rate limiting zones
    limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
    limit_req_zone $binary_remote_addr zone=login:10m rate=5r/m;

    # NFC play page
    location ~ ^/nfc/(?<nfc_code>.+)$ {
        alias /home/admin/artouch/static/nfc/;
        expires 7d;
        add_header Cache-Control "public, immutable";
        add_header X-Content-Type-Options "nosniff";
    }

    # API proxy
    location /api/ {
        limit_req zone=api burst=20 nodelay;
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 60s;
        proxy_connect_timeout 60s;
    }

    # Admin SPA
    location /admin/ {
        alias /home/admin/artouch/frontend/dist/;
        try_files $uri $uri/ /admin/index.html;
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
            expires 30d;
            add_header Cache-Control "public, immutable";
        }
    }

    # Health check
    location /health {
        access_log off;
        return 200 "OK\n";
        add_header Content-Type text/plain;
    }

    # Root redirect
    location = / {
        return 302 /admin/;
    }
}
EOF

    sed -i "s/DOMAIN_PLACEHOLDER/${DOMAIN}/g" "${NGINX_SSL_CONF}"
    log_info "Nginx SSL config saved to ${NGINX_SSL_CONF}"
}

# Get SSL certificate
get_certificate() {
    log_info "Requesting SSL certificate for ${DOMAIN}..."

    # Test Nginx config first
    if ! nginx -t; then
        log_error "Nginx configuration test failed"
        exit 1
    fi

    # Enable the site
    ln -sf "${NGINX_SSL_CONF}" /etc/nginx/sites-enabled/ 2>/dev/null || true
    systemctl reload nginx

    # Request certificate (standalone mode)
    certbot certonly --standalone \
        --non-interactive \
        --agree-tos \
        --email "${EMAIL}" \
        --domains "${DOMAIN}" \
        --pre-hook "systemctl stop nginx" \
        --post-hook "systemctl start nginx" \
        || { log_error "Certificate request failed"; exit 1; }

    log_info "Certificate obtained successfully!"
    log_info "Certificate location: ${CERT_DIR}"
}

# Renew certificate
renew_certificate() {
    log_info "Renewing SSL certificate..."
    certbot renew --nginx --post-hook "systemctl reload nginx"
    log_info "Renewal complete"
}

# Setup auto-renewal
setup_auto_renew() {
    log_info "Setting up automatic renewal..."

    # Create renewal cron job
    cat > /etc/cron.d/certbot-renew << 'EOF'
# Certbot automatic renewal
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
0 0,12 * * * root python3 -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew --post-hook "systemctl reload nginx"
EOF

    chmod 644 /etc/cron.d/certbot-renew
    log_info "Auto-renewal configured (runs twice daily)"
}

# Main
main() {
    check_root

    case "${1:-}" in
        --install)
            install_certbot
            generate_nginx_ssl
            get_certificate
            setup_auto_renew
            ;;
        --renew)
            renew_certificate
            ;;
        --generate-conf)
            install_certbot
            generate_nginx_ssl
            ;;
        *)
            echo "Usage: $0 {--install|--renew|--generate-conf}"
            echo ""
            echo "  --install      Install certbot, generate config, and get certificate"
            echo "  --renew        Renew existing certificate"
            echo "  --generate-conf  Generate Nginx SSL config only (no cert)"
            echo ""
            echo "Environment variables:"
            echo "  DOMAIN=${DOMAIN}"
            echo "  EMAIL=${EMAIL}"
            ;;
    esac
}

main "$@"
